set(_CATKIN_CURRENT_PACKAGE "pairs_uav_dji_tello_api")
set(pairs_uav_dji_tello_api_VERSION "1.0.0")
set(pairs_uav_dji_tello_api_MAINTAINER "Thanh Nguyen Canh <canhthanh@vnu.edu.vn>")
set(pairs_uav_dji_tello_api_PACKAGE_FORMAT "2")
set(pairs_uav_dji_tello_api_BUILD_DEPENDS "cmake_modules" "geometry_msgs" "mavros_msgs" "pairs_lib" "pairs_msgs" "pairs_uav_hw_api" "nav_msgs" "pluginlib" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(pairs_uav_dji_tello_api_BUILD_EXPORT_DEPENDS "cmake_modules" "geometry_msgs" "mavros_msgs" "pairs_lib" "pairs_msgs" "pairs_uav_hw_api" "nav_msgs" "pluginlib" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(pairs_uav_dji_tello_api_BUILDTOOL_DEPENDS "catkin")
set(pairs_uav_dji_tello_api_BUILDTOOL_EXPORT_DEPENDS )
set(pairs_uav_dji_tello_api_EXEC_DEPENDS "cmake_modules" "geometry_msgs" "mavros_msgs" "pairs_lib" "pairs_msgs" "pairs_uav_hw_api" "nav_msgs" "pluginlib" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(pairs_uav_dji_tello_api_RUN_DEPENDS "cmake_modules" "geometry_msgs" "mavros_msgs" "pairs_lib" "pairs_msgs" "pairs_uav_hw_api" "nav_msgs" "pluginlib" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(pairs_uav_dji_tello_api_TEST_DEPENDS )
set(pairs_uav_dji_tello_api_DOC_DEPENDS )
set(pairs_uav_dji_tello_api_URL_WEBSITE "")
set(pairs_uav_dji_tello_api_URL_BUGTRACKER "")
set(pairs_uav_dji_tello_api_URL_REPOSITORY "")
set(pairs_uav_dji_tello_api_DEPRECATED "")